apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy68
  labels:
    app: autodeploy68
  namespace: namespace-workflow-1714540639425
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy68
  template:
    metadata:
      labels:
        app: autodeploy68
    spec:
      containers:
        - name: autodeploy68
          image: acrworkflow1714540639425.azurecr.io/image-workflow-1714540639425:latest
          ports:
            - containerPort: 5000