apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy99
  labels:
    app: autodeploy99
  namespace: namespace-workflow-1714462961170
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy99
  template:
    metadata:
      labels:
        app: autodeploy99
    spec:
      containers:
        - name: autodeploy99
          image: acrworkflow1714462961170.azurecr.io/image-workflow-1714462961170:latest
          ports:
            - containerPort: 5000